spring.application.name=cart-service

server.port=8084


spring.datasource.url=jdbc:postgresql://localhost:5432/cart_service_db
spring.datasource.username=hariharanr
spring.datasource.password=postgres


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



product.service.url=http://localhost:8082


order.service.url=http://localhost:8083

